# ref : https://www.unicode.org/charts/PDF/U1FB00.pdf
char_2x2 = [
[' ', 0x0020, 'SPACE'],
['▝', 0x259D, 'QUADRANT UPPER RIGHT'],
['▘', 0x2598, 'QUADRANT UPPER LEFT'],
['▀', 0x2580, 'UPPER HALF BLOCK'],

['▗', 0x2597, 'QUADRANT LOWER RIGHT'],

['▐', 0x2590, 'RIGHT HALF BLOCK'],

['▚', 0x259A, 'QUADRANT UPPER LEFT AND LOWER RIGHT'],

['▜', 0x259C, 'QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER RIGHT'],


['▖', 0x2596, 'QUADRANT LOWER LEFT'],

['▞', 0x259E, 'QUADRANT UPPER RIGHT AND LOWER LEFT'],


['▌', 0x258C, 'LEFT HALF BLOCK'],

['▛', 0x259B, 'QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER LEFT'],



['▄', 0x2584, 'LOWER HALF BLOCK'],
['▟', 0x259F, 'QUADRANT UPPER RIGHT AND LOWER LEFT AND LOWER RIGHT'],
['▙', 0x2599, 'QUADRANT UPPER LEFT AND LOWER LEFT AND LOWER RIGHT'],
['█', 0x2588, 'FULL BLOCK'],
]